version: "3.9"

services:
  #db-beacon:
  #  image: mongo
  #  hostname: db-beacon
  #  ports:
  #    - 27018:27017
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example
  #  command: --wiredTigerCacheSizeGB 4

  #db-beacon-load:
  #  image: mongo
  #  links:
  #    - db-beacon
  #  volumes:
  #    - ./db/CINECA_synthetic_cohort_EUROPE_UK1/bff:/data  
  #    - ./db/bff2mongodb_container.sh:/data/bff2mongodb.sh  
  #  command: bash -c "cp /data/bff2mongodb.sh bff2mongodb.sh && bash bff2mongodb.sh"
  #  depends_on:
  #    - db-beacon

  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
          echo "sleep for 60sec"
          sleep 60 
          python app/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=beacon
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - USERNAME=root
      - PASSWORD=example
        #depends_on:
        #- db-beacon
    networks:
      - beacon2-pi-api_pub

  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #    ME_CONFIG_MONGODB_URL: mongodb://root:example@db-beacon:27017/
  #  depends_on:
  #    - db-beacon

networks:
  beacon2-pi-api_pub:
    external: true
